[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'dag/vim-fish'

# 2020/9/4 Language serever plugin
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'

# # 2020/9/16 File tree
# [[plugins]]
# repo = 'scrooloose/nerdtree'
# # With persistent window accross tabs
# [[plugins]]
# repo = 'jistr/vim-nerdtree-tabs'
# # With Git status
# [[plugins]]
# repo = 'Xuyuanp/nerdtree-git-plugin'

# 2020/9/16 toml syntax
[[plugins]]
repo = 'cespare/vim-toml'

# Color schemme
# https://cocopon.me/blog/2013/02/hybrid/
# https://github.com/w0ng/vim-hybrid
[[plugins]]
repo = "w0ng/vim-hybrid"

[[plugins]]
repo = "joshdick/onedark.vim"

# Git diff highlight
[[plugins]]
repo = "airblade/vim-gitgutter"

# SaTySFi highlight
[[plugins]]
repo = "qnighy/satysfi.vim"
# repo = "~/dev/git/com/github/TonalidadeHidrica/satysfi.vim/"

# Search for selection
[[plugins]]
repo = "bronson/vim-visual-star-search"

# editorconfig
[[plugins]]
repo = 'editorconfig/editorconfig-vim'

# Capture Ex output to another window
[[plugins]]
repo = 'tyru/capture.vim'

# Highlight Wolfram Script
[[plugins]]
repo = 'voldikss/vim-mma'

# treesitter
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
merged = 0

# JSONC support (for coc-settings.json)
[[plugins]]
repo = 'kevinoid/vim-jsonc'

# Show the entire stack of highlight stack
[[plugins]]
repo = 'gerw/vim-HiLinkTrace'

# Plugin for hilighting RDF
[[plugins]]
repo = 'niklasl/vim-rdf'

# Extend textobj
[[plugins]]
repo = 'kana/vim-textobj-user'

# Use an arbitrary character as a textobj separator
[[plugins]]
repo = 'thinca/vim-textobj-between'

# Syntax highlight for wgsl
[[plugins]]
repo = 'DingDean/wgsl.vim'

# 2023/01/01 Seeking for better markdown tool
[[plugins]]
repo = 'godlygeek/tabular'
[[plugins]]
repo = 'preservim/vim-markdown'

# Profile startup time
[[plugins]]
repo = 'dstein64/vim-startuptime'

# MediaWiki (Wikipedia) syntax highlighting etc.
[[plugins]]
repo = 'chikamichi/mediawiki.vim'

# GhostText (edit browser's textbox with vim)
[[plugins]]
repo = 'raghur/vim-ghost'

# Undo tree
[[plugins]]
repo = 'mbbill/undotree'
